services:
  postgres1:
    image: postgres:17.0
    #command: '/var/lib/postgresql/data/migrate/initdb.sh'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: '/var/lib/postgresql/data/pgdata'
      MIGRATION_DIR: '/migrate'
    volumes:
      - ./migrate/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./migrate:/migrate
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  cybertasks:
    build:
      context: ./
      dockerfile: dockerfile
    environment:
      PG_PASSWORD: 'taskpass'
      WORKSPACE: /app
      CONFIG_FILE: /app/config.yaml
    ports:
      - '7730:7730'
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./logs/cybertask.log:/app/tmp/log.txt:rw
    depends_on:
      postgres1:
        condition: service_healthy
    networks:
      tasknet:
  ext1:
    build:
      context: ./pkg/external-service
      dockerfile: dockerfile
    environment:
      EXT_SERVICE_ADDR: 'localhost:7731'
    depends_on:
      postgres1:
        condition: service_healthy
    ports:
      - '7731:7731'
    networks:
      tasknet:
  ext2:
    build:
      context: ./pkg/external-service
      dockerfile: dockerfile
    environment:
      EXT_SERVICE_ADDR: 'localhost:7732'
    depends_on:
      postgres1:
        condition: service_healthy
    ports:
      - '7732:7732'
    networks:
      tasknet:
networks:
  tasknet:
    driver: bridge  